services:
  app:
    image: ${DOCKER_USERNAME}/nextstation-be:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT:-3306}
      DB_NAME: ${DB_NAME}
      
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      
      REDIS_HOST: redis
      REDIS_PORT: 6379
      
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      
      JWT_SECRET: ${JWT_SECRET}
      
      AWS_REGION: ${AWS_REGION}
      AWS_S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME}
      
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}

      KAKAO_OAUTH_CLIENT_ID: ${KAKAO_OAUTH_CLIENT_ID}
      KAKAO_OAUTH_CLIENT_SECRET: ${KAKAO_OAUTH_CLIENT_SECRET}
      KAKAO_OAUTH_REDIRECT_URIS: ${KAKAO_OAUTH_REDIRECT_URIS}

      DISCORD_ERROR_WEBHOOK_URL: ${DISCORD_ERROR_WEBHOOK_URL}
      DISCORD_REPORT_WEBHOOK_URL: ${DISCORD_REPORT_WEBHOOK_URL}
      REPORT_CRON_DAILY: ${REPORT_CRON_DAILY:-0 0 9 * * *}
      REPORT_CRON_WEEKLY: ${REPORT_CRON_WEEKLY:-0 10 9 * * MON}
    depends_on:
      redis:
        condition: service_healthy
    restart: always

  redis:
    image: redis:7.2-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: always

volumes:
  redis-data:
